name = "ParallelLinearOracles"
uuid = "50334860-de34-4943-b2b8-ae20f493b614"
authors = ["matbesancon <mathieu.besancon@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
